FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /app

COPY pom.xml .
RUN mvn -B -DskipTests dependency:go-offline

COPY src ./src
RUN mvn -B -DskipTests clean package

FROM eclipse-temurin:21-jdk AS runner
WORKDIR /app
COPY --from=builder /app/target/analytics-service-0.0.1-SNAPSHOT.jar /app/app.jar
EXPOSE 4002
ENTRYPOINT ["java","-jar","/app/app.jar"]
